### ISSUE TITLE
Can we get details on the deployment pipeline?

### ISSUE THREAD

**Issue by dylankenneally** [xdesro/sex-work-exclusive-tech-companies#39]
I'm guessing (hoping) the deployment pipeline to https://sex-work-exclusive-companies.tech/ is automated? 

If so, can we get details of how it functions so devs can emulate it locally to make sure their changes don't break anything.

If it's not automated, I think it would be a good idea (via a promotion scheme or similar).

And if that's a no-go, could we get details of the dispatching server so we can emulate that? I.e. nginx, apache, gws, etc.

**Comment by xdesro** [comment]
Hey @dylankenneally — the site is continuously deployed by Netlify, which redeploys every time the `main` branch is updated. Netlify spins up a Node env and runs `npm run generate`, and serves the resulting generated directory!
