### ISSUE TITLE
Discussions in GitHub

### ISSUE THREAD

**Issue by dylankenneally** [xdesro/sex-work-exclusive-tech-companies#40]
Following on from our Twitter chat @xdesro, I've got a whole bunch of ideas for this project I'd like to run by you & anyone else involved in the project. 

It's not a crazy amount of ideas, but some of them would be new feature development, creating new workflows, potential CTA's, and UX stuff.

I think it would be worth turning on the Discussions feature for the repo to let that happen - thoughts?

**Comment by xdesro** [comment]
Sounds great to me, I _believe_ I've just set that up on here!
